// <auto-generated />
using System;
using Luno_platform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luno_platform.Migrations
{
    [DbContext(typeof(LunoDBContext))]
    [Migration("20251118084916_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Luno_platform.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Luno_platform.Models.Classes", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClassID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Luno_platform.Models.CourseContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Url1")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Url2")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Url3")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Url4")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Url5")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Url6")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("CourseContents");
                });

            modelBuilder.Entity("Luno_platform.Models.Courses", b =>
                {
                    b.Property<int>("Courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Courseid"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("contentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("instructorID")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Courseid");

                    b.HasIndex("SubjectId");

                    b.HasIndex("contentId")
                        .IsUnique();

                    b.HasIndex("instructorID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Luno_platform.Models.Exams", b =>
                {
                    b.Property<int>("ExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamID"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumOfQuestions")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<int>("attempt")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.Property<int>("degreeExam")
                        .HasColumnType("int");

                    b.Property<int>("instructorID")
                        .HasColumnType("int");

                    b.Property<int>("subjectId")
                        .HasColumnType("int");

                    b.HasKey("ExamID");

                    b.HasIndex("ClassId");

                    b.HasIndex("instructorID");

                    b.HasIndex("subjectId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Luno_platform.Models.Exams_contentcs", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("contentid")
                        .HasColumnType("int");

                    b.HasKey("ExamId", "contentid");

                    b.HasIndex("contentid");

                    b.ToTable("Exams_contentcs");
                });

            modelBuilder.Entity("Luno_platform.Models.Instructor", b =>
                {
                    b.Property<int>("instructorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("instructorID"));

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("instructorID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Luno_platform.Models.Parent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("Luno_platform.Models.Payments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<decimal>("amountPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("StudentID");

                    b.HasIndex("courseId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Luno_platform.Models.Question", b =>
                {
                    b.Property<int>("questionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("questionID"));

                    b.Property<int?>("ExamId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("chooseA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chooseB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chooseC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chooseD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correctAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("degree")
                        .HasColumnType("int");

                    b.Property<string>("questionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("questionID");

                    b.HasIndex("ExamId");

                    b.HasIndex("TaskId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Luno_platform.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("branch")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("classId")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("classId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Luno_platform.Models.StudentAnswer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("ExamId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("studentanswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("ExamId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentID");

                    b.HasIndex("TaskId");

                    b.ToTable("StudentAnswers");
                });

            modelBuilder.Entity("Luno_platform.Models.StudentStatistics", b =>
                {
                    b.Property<int>("Statistics_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Statistics_ID"));

                    b.Property<int?>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("degree")
                        .HasColumnType("int");

                    b.HasKey("Statistics_ID");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentID");

                    b.HasIndex("TaskId");

                    b.ToTable("StudentStatistics");
                });

            modelBuilder.Entity("Luno_platform.Models.Student_Courses", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Student_Courses");
                });

            modelBuilder.Entity("Luno_platform.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectNameAR")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubjectNameEN")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Luno_platform.Models.Subject_Classes", b =>
                {
                    b.Property<int>("classId")
                        .HasColumnType("int");

                    b.Property<int>("subjectId")
                        .HasColumnType("int");

                    b.HasKey("classId", "subjectId");

                    b.HasIndex("subjectId");

                    b.ToTable("Subject_Classes");
                });

            modelBuilder.Entity("Luno_platform.Models.Task_content", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("contentid")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "contentid");

                    b.HasIndex("contentid");

                    b.ToTable("Task_content");
                });

            modelBuilder.Entity("Luno_platform.Models.Tasks", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseContentId")
                        .HasColumnType("int");

                    b.Property<int>("NumOfQuestions")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("createdAT")
                        .HasColumnType("datetime2");

                    b.Property<int>("instructorId")
                        .HasColumnType("int");

                    b.HasKey("TaskID");

                    b.HasIndex("ClassId");

                    b.HasIndex("CourseContentId");

                    b.HasIndex("instructorId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Luno_platform.Models.Teacher_payment", b =>
                {
                    b.Property<int>("paymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("instructorID")
                        .HasColumnType("int");

                    b.HasKey("paymentID");

                    b.HasIndex("AdminID");

                    b.HasIndex("instructorID");

                    b.ToTable("Teacher_payment");
                });

            modelBuilder.Entity("Luno_platform.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nationalID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("secondName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Luno_platform.Models.instructor_classescs", b =>
                {
                    b.Property<int>("instructorId")
                        .HasColumnType("int");

                    b.Property<int>("classId")
                        .HasColumnType("int");

                    b.HasKey("instructorId", "classId");

                    b.HasIndex("classId");

                    b.ToTable("instructor_classescs");
                });

            modelBuilder.Entity("Luno_platform.Models.Courses", b =>
                {
                    b.HasOne("Luno_platform.Models.Subject", "Subjects")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.CourseContent", "CourseContent")
                        .WithOne("courses")
                        .HasForeignKey("Luno_platform.Models.Courses", "contentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Instructor", "Instructor")
                        .WithMany("courses")
                        .HasForeignKey("instructorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseContent");

                    b.Navigation("Instructor");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Luno_platform.Models.Exams", b =>
                {
                    b.HasOne("Luno_platform.Models.Classes", "Classess")
                        .WithMany("Exams")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Instructor", "Instructor")
                        .WithMany("Exams")
                        .HasForeignKey("instructorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Classess");

                    b.Navigation("Instructor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Luno_platform.Models.Exams_contentcs", b =>
                {
                    b.HasOne("Luno_platform.Models.Exams", "Exams")
                        .WithMany("Exams_Content")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.CourseContent", "CourseContent")
                        .WithMany("Exams_Content")
                        .HasForeignKey("contentid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseContent");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Luno_platform.Models.Instructor", b =>
                {
                    b.HasOne("Luno_platform.Models.Subject", "Subject")
                        .WithMany("Instructors")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Users", "User")
                        .WithOne("Instructor")
                        .HasForeignKey("Luno_platform.Models.Instructor", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Luno_platform.Models.Parent", b =>
                {
                    b.HasOne("Luno_platform.Models.Users", "User")
                        .WithOne("parent")
                        .HasForeignKey("Luno_platform.Models.Parent", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Luno_platform.Models.Payments", b =>
                {
                    b.HasOne("Luno_platform.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Courses", "Courses")
                        .WithMany("Payments")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Luno_platform.Models.Question", b =>
                {
                    b.HasOne("Luno_platform.Models.Exams", "Exams")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Luno_platform.Models.Tasks", "Tasks")
                        .WithMany("Questions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exams");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Luno_platform.Models.Student", b =>
                {
                    b.HasOne("Luno_platform.Models.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Luno_platform.Models.Users", "User")
                        .WithOne("student")
                        .HasForeignKey("Luno_platform.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Classes", "Classes")
                        .WithMany("Students")
                        .HasForeignKey("classId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Luno_platform.Models.StudentAnswer", b =>
                {
                    b.HasOne("Luno_platform.Models.Exams", "Exams")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Luno_platform.Models.Question", "Question")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Luno_platform.Models.Student", "Student")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Tasks", "Tasks")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exams");

                    b.Navigation("Question");

                    b.Navigation("Student");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Luno_platform.Models.StudentStatistics", b =>
                {
                    b.HasOne("Luno_platform.Models.Exams", "Exams")
                        .WithMany("StudentStatistics")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Luno_platform.Models.Student", "Student")
                        .WithMany("StudentStatistics")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Tasks", "Tasks")
                        .WithMany("StudentStatistics")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exams");

                    b.Navigation("Student");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Luno_platform.Models.Student_Courses", b =>
                {
                    b.HasOne("Luno_platform.Models.Courses", "Course")
                        .WithMany("Student_Courses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Student", "Student")
                        .WithMany("Student_Courses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Luno_platform.Models.Subject_Classes", b =>
                {
                    b.HasOne("Luno_platform.Models.Classes", "Classes")
                        .WithMany("Subject_Classes")
                        .HasForeignKey("classId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Subject", "Subject")
                        .WithMany("Subject_Classes")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Luno_platform.Models.Task_content", b =>
                {
                    b.HasOne("Luno_platform.Models.Tasks", "Tasks")
                        .WithMany("Task_Contents")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.CourseContent", "CourseContent")
                        .WithMany("Task_Contents")
                        .HasForeignKey("contentid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseContent");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Luno_platform.Models.Tasks", b =>
                {
                    b.HasOne("Luno_platform.Models.Classes", "Classes")
                        .WithMany("Tasks")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.CourseContent", null)
                        .WithMany("Tasks")
                        .HasForeignKey("CourseContentId");

                    b.HasOne("Luno_platform.Models.Instructor", "Instructor")
                        .WithMany("Tasks")
                        .HasForeignKey("instructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Luno_platform.Models.Teacher_payment", b =>
                {
                    b.HasOne("Luno_platform.Models.Admin", "Admin")
                        .WithMany("Teacher_Payments")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Instructor", "Instructor")
                        .WithMany("Teacher_Payments")
                        .HasForeignKey("instructorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Luno_platform.Models.instructor_classescs", b =>
                {
                    b.HasOne("Luno_platform.Models.Classes", "classes")
                        .WithMany("instructor_classescs")
                        .HasForeignKey("classId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Luno_platform.Models.Instructor", "Instructor")
                        .WithMany("instructor_classescs")
                        .HasForeignKey("instructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("classes");
                });

            modelBuilder.Entity("Luno_platform.Models.Admin", b =>
                {
                    b.Navigation("Teacher_Payments");
                });

            modelBuilder.Entity("Luno_platform.Models.Classes", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Students");

                    b.Navigation("Subject_Classes");

                    b.Navigation("Tasks");

                    b.Navigation("instructor_classescs");
                });

            modelBuilder.Entity("Luno_platform.Models.CourseContent", b =>
                {
                    b.Navigation("Exams_Content");

                    b.Navigation("Task_Contents");

                    b.Navigation("Tasks");

                    b.Navigation("courses");
                });

            modelBuilder.Entity("Luno_platform.Models.Courses", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Student_Courses");
                });

            modelBuilder.Entity("Luno_platform.Models.Exams", b =>
                {
                    b.Navigation("Exams_Content");

                    b.Navigation("Questions");

                    b.Navigation("StudentAnswers");

                    b.Navigation("StudentStatistics");
                });

            modelBuilder.Entity("Luno_platform.Models.Instructor", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Tasks");

                    b.Navigation("Teacher_Payments");

                    b.Navigation("courses");

                    b.Navigation("instructor_classescs");
                });

            modelBuilder.Entity("Luno_platform.Models.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Luno_platform.Models.Question", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("Luno_platform.Models.Student", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("StudentAnswers");

                    b.Navigation("StudentStatistics");

                    b.Navigation("Student_Courses");
                });

            modelBuilder.Entity("Luno_platform.Models.Subject", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Exams");

                    b.Navigation("Instructors");

                    b.Navigation("Subject_Classes");
                });

            modelBuilder.Entity("Luno_platform.Models.Tasks", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("StudentAnswers");

                    b.Navigation("StudentStatistics");

                    b.Navigation("Task_Contents");
                });

            modelBuilder.Entity("Luno_platform.Models.Users", b =>
                {
                    b.Navigation("Instructor");

                    b.Navigation("parent");

                    b.Navigation("student");
                });
#pragma warning restore 612, 618
        }
    }
}
